# Generated by Django 4.0 on 2021-12-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_creation_date_item_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creation_date',
            field=models.DateTimeField(default='2021-12-27 11:08:14.391606', verbose_name='date created'),
        ),
    ]
