# Generated by Django 4.0 on 2021-12-27 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 11, 31, 5, 304663), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='item',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 11, 31, 5, 304663), verbose_name='date created'),
        ),
    ]
